# Generated by Django 5.1.3 on 2024-11-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricitySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('electricity_usage', models.PositiveIntegerField(help_text='Consumo mensual estimado en kWh')),
                ('num_appliances', models.PositiveIntegerField(help_text='Número de electrodomésticos en tu hogar')),
                ('renewable_usage', models.BooleanField(default=False, help_text='¿Usas fuentes de energía renovables?')),
            ],
        ),
    ]
